version: '3.3'

services:

  prometheus:
    image: madson7/prometheus_alpine
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/var/lib/prometheus
    networks:
      - backend
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./conf/grafana/grafana.config
    networks:
      - backend
      - frontend
    ports:
      - 3000:3000

networks:
  frontend:
  backend:

volumes:
    prometheus_data:
    grafana_data: