version: '3.3'

services:

  prometheus:
    image: madson7/prometheus_alpine
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/var/lib/prometheus
    networks:
      - backend
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./conf/grafana/grafana.config
    networks:
      - backend
      - frontend
    ports:
      - 3000:3000

  consul:
    image: consul
    ports:
      - "8500:8500"
    networks:
      - backend
      - frontend
  node-exporter-1:
    image: prom/node-exporter:v0.18.1
    ports:
      - "9100:9100"
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
    prometheus_data:
    grafana_data: