{
 "title": "System",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disco Livre",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{instance=~\"34.66.70.236:9101\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"34.66.70.236:9101\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=~\"34.66.70.236:9101\", mountpoint=\"/\"}",
     "legendFormat": "Root {{mountpoint}}"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"34.66.70.236:9101\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total de node exporter's",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(node_context_switches_total)",
     "legendFormat": "Node exporter linux"
    },
    { "expr": "count(mikrotik_system_uptime)", "legendFormat": "Node exporter mikrotik" },
    {
     "expr": "count(ping_loss_percent)",
     "legendFormat": "Ping, Pacotes e Latência de serviços"
    }
   ]
  },
  {
   "title": "Uso de CPU dos hosts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"34.66.70.236:9101\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"34.66.70.236:9101\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"34.66.70.236:9101\"}) by (cpu))",
     "legendFormat": "{{34.66.70.236:9101}}"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"170.82.181.4:15807\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"170.82.181.4:15807\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"170.82.181.4:15807\"}) by (cpu))",
     "legendFormat": "{{170.82.181.4:15807}}"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"170.82.181.4:15806\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"170.82.181.4:15806\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"170.82.181.4:15806\"}) by (cpu))",
     "legendFormat": "{{170.82.181.4:15806}}"
    },
    {
     "expr": "mikrotik_system_cpu_load{address=\"192.168.0.10\",boardname=\"x86\",instance=\"170.82.181.4:15808\",job=\"consul-services\",version=\"6.43.1 (stable)\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uso de memória por node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mikrotik_system_total_memory-(mikrotik_system_total_memory-mikrotik_system_free_memory)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes-(node_memory_MemTotal_bytes-node_memory_MemFree_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total de container",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Uso de CPU por contêiner",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 25 },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{instance=\"34.66.70.236:8080\",image!=\"\"}[5m]) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Uso de memória por contêiner",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"34.66.70.236:8080\",image!=\"\"}",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Porcentagem de perda de ping - PUBG",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ping_loss_percent{ip=\"150.109.27.214\"}",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "ping_loss_percent{ip=\"169.57.199.205\"}",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "ping_loss_percent{ip=\"201.159.159.129\"}",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "ping_loss_percent{ip=\"49.51.42.110\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Porcentagem de perda de ping - Facebook e twitter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ping_loss_percent{target=\"facebook.com\"}",
     "legendFormat": "{{target}} IPV{{ip_version}}"
    },
    {
     "expr": "ping_loss_percent{target=\"twitter.com\"}",
     "legendFormat": "{{target}} IPV{{ip_version}}"
    }
   ]
  },
  {
   "title": "Tempo de Ida e Volta (RTT) - PUBG",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(ping_rtt_ms{ip=\"150.109.27.214\"})/4"
    },
    {
     "expr": "sum(ping_rtt_ms{ip=\"169.57.199.205\"})/4"
    },
    {
     "expr": "sum(ping_rtt_ms{ip=\"201.159.159.129\"})/4"
    },
    {
     "expr": "sum(ping_rtt_ms{ip=\"49.51.42.110\"})/4"
    }
   ]
  },
  {
   "title": "Tempo de Ida e Volta (RTT) - Facebook e twitter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(ping_rtt_ms{target=\"facebook.com\"})/4"
    },
    {
     "expr": "sum(ping_rtt_ms{target=\"twitter.com\"})/4"
    }
   ]
  }
 ]
}