global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'monitoring'
rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'consul-services'
    scrape_interval: 1s
    consul_sd_configs:
    - server: 'consul:8500'
    relabel_configs:
    - source_labels: ['__meta_consul_service_id']
      action: drop
      regex: consul

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 1s
    static_configs:
         - targets: ['jacare.tech:19999']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080